version: 1.0.{build}
branches:
  only:
  - master
  - development
  - ^version-.*$
image: Visual Studio 2019
configuration: Release
clone_depth: 1
before_build:
- cmd: dotnet restore
build:
  project: MyTested.AspNetCore.Mvc.sln
  verbosity: minimal
test_script:
- cmd: dotnet test "samples/MusicStore/MusicStore.Test/MusicStore.Test.csproj" --configuration Release --no-build
- cmd: dotnet test "samples/Blog/Blog.Test/Blog.Test.csproj" --configuration Release --no-build
- cmd: dotnet test "samples/ApplicationParts/ApplicationParts.Test/ApplicationParts.Test.csproj" --configuration Release --no-build
- cmd: dotnet test "samples/Autofac/Autofac.AssemblyInit.Test/Autofac.AssemblyInit.Test.csproj" --configuration Release --no-build
- cmd: dotnet test "samples/Autofac/Autofac.NoContainerBuilder.Test/Autofac.NoContainerBuilder.Test.csproj" --configuration Release --no-build
- cmd: dotnet test "samples/Autofac/Autofac.Test/Autofac.Test.csproj" --configuration Release --no-build
- cmd: dotnet test "samples/Configuration/Test.Core.MissingAppPackage/Test.Core.MissingAppPackage.csproj" --configuration Release --no-build
- cmd: dotnet test "samples/Configuration/Test.DifferentEnvironment/Test.DifferentEnvironment.csproj" --configuration Release --no-build
- cmd: dotnet test "samples/Configuration/Test.ExplicitNoStartupType/Test.ExplicitNoStartupType.csproj" --configuration Release --no-build
- cmd: dotnet test "samples/Configuration/Test.FullFramework.NoCompilationContext/Test.FullFramework.NoCompilationContext.csproj" --configuration Release --no-build
- cmd: dotnet test "samples/Configuration/Test.MissingStartupType/Test.MissingStartupType.csproj" --configuration Release --no-build
- cmd: dotnet test "samples/Configuration/Test.NoAsync/Test.NoAsync.csproj" --configuration Release --no-build
- cmd: dotnet test "samples/Configuration/Test.NoStartupType/Test.NoStartupType.csproj" --configuration Release --no-build
- cmd: dotnet test "samples/Configuration/Test.WrongStartupType/Test.WrongStartupType.csproj" --configuration Release --no-build
- cmd: dotnet test "samples/Configuration/Test.WrongTestAssembly/Test.WrongTestAssembly.csproj" --configuration Release --no-build
- cmd: dotnet test "samples/Configuration/Test.WrongWebAssembly/Test.WrongWebAssembly.csproj" --configuration Release --no-build
- cmd: dotnet test "samples/FullFramework/FullFramework.AssemblyInit.Test/FullFramework.AssemblyInit.Test.csproj" --configuration Release --no-build
- cmd: dotnet test "samples/FullFramework/FullFramework.Test/FullFramework.Test.csproj" --configuration Release --no-build
- cmd: dotnet test "samples/Lite/Lite.Test/Lite.Test.csproj" --configuration Release --no-build
- cmd: dotnet test "samples/NoStartup/NoStartup.Test/NoStartup.Test.csproj" --configuration Release --no-build
- cmd: dotnet test "samples/WebStartup/WebStartup.Test/WebStartup.Test.csproj" --configuration Release --no-build
- cmd: dotnet test "test/MyTested.AspNetCore.Mvc.Abstractions.Test/MyTested.AspNetCore.Mvc.Abstractions.Test.csproj" --configuration Release --no-build
- cmd: dotnet test "test/MyTested.AspNetCore.Mvc.Authentication.Test/MyTested.AspNetCore.Mvc.Authentication.Test.csproj" --configuration Release --no-build
- cmd: dotnet test "test/MyTested.AspNetCore.Mvc.Caching.Test/MyTested.AspNetCore.Mvc.Caching.Test.csproj" --configuration Release --no-build
- cmd: dotnet test "test/MyTested.AspNetCore.Mvc.Configuration.Test/MyTested.AspNetCore.Mvc.Configuration.Test.csproj" --configuration Release --no-build
- cmd: dotnet test "test/MyTested.AspNetCore.Mvc.Controllers.ActionResults.Test/MyTested.AspNetCore.Mvc.Controllers.ActionResults.Test.csproj" --configuration Release --no-build
- cmd: dotnet test "test/MyTested.AspNetCore.Mvc.Controllers.Attributes.Test/MyTested.AspNetCore.Mvc.Controllers.Attributes.Test.csproj" --configuration Release --no-build
- cmd: dotnet test "test/MyTested.AspNetCore.Mvc.Controllers.Test/MyTested.AspNetCore.Mvc.Controllers.Test.csproj" --configuration Release --no-build
- cmd: dotnet test "test/MyTested.AspNetCore.Mvc.Controllers.Views.ActionResults.Test/MyTested.AspNetCore.Mvc.Controllers.Views.ActionResults.Test.csproj" --configuration Release --no-build
- cmd: dotnet test "test/MyTested.AspNetCore.Mvc.Controllers.Views.Test/MyTested.AspNetCore.Mvc.Controllers.Views.Test.csproj" --configuration Release --no-build
- cmd: dotnet test "test/MyTested.AspNetCore.Mvc.DataAnnotations.Test/MyTested.AspNetCore.Mvc.DataAnnotations.Test.csproj" --configuration Release --no-build
- cmd: dotnet test "test/MyTested.AspNetCore.Mvc.DependencyInjection.Test/MyTested.AspNetCore.Mvc.DependencyInjection.Test.csproj" --configuration Release --no-build
- cmd: dotnet test "test/MyTested.AspNetCore.Mvc.EntityFrameworkCore.Test/MyTested.AspNetCore.Mvc.EntityFrameworkCore.Test.csproj" --configuration Release --no-build
- cmd: dotnet test "test/MyTested.AspNetCore.Mvc.Helpers.Test/MyTested.AspNetCore.Mvc.Helpers.Test.csproj" --configuration Release --no-build
- cmd: dotnet test "test/MyTested.AspNetCore.Mvc.Http.Test/MyTested.AspNetCore.Mvc.Http.Test.csproj" --configuration Release --no-build
- cmd: dotnet test "test/MyTested.AspNetCore.Mvc.Licensing.Test/MyTested.AspNetCore.Mvc.Licensing.Test.csproj" --configuration Release --no-build
- cmd: dotnet test "test/MyTested.AspNetCore.Mvc.Lite.Test/MyTested.AspNetCore.Mvc.Lite.Test.csproj" --configuration Release --no-build
- cmd: dotnet test "test/MyTested.AspNetCore.Mvc.Models.Test/MyTested.AspNetCore.Mvc.Models.Test.csproj" --configuration Release --no-build
- cmd: dotnet test "test/MyTested.AspNetCore.Mvc.ModelState.Test/MyTested.AspNetCore.Mvc.ModelState.Test.csproj" --configuration Release --no-build
- cmd: dotnet test "test/MyTested.AspNetCore.Mvc.Options.Test/MyTested.AspNetCore.Mvc.Options.Test.csproj" --configuration Release --no-build
- cmd: dotnet test "test/MyTested.AspNetCore.Mvc.Routing.Test/MyTested.AspNetCore.Mvc.Routing.Test.csproj" --configuration Release --no-build
- cmd: dotnet test "test/MyTested.AspNetCore.Mvc.Session.Test/MyTested.AspNetCore.Mvc.Session.Test.csproj" --configuration Release --no-build
- cmd: dotnet test "test/MyTested.AspNetCore.Mvc.TempData.Test/MyTested.AspNetCore.Mvc.TempData.Test.csproj" --configuration Release --no-build
- cmd: dotnet test "test/MyTested.AspNetCore.Mvc.Test/MyTested.AspNetCore.Mvc.Test.csproj" --configuration Release --no-build
- cmd: dotnet test "test/MyTested.AspNetCore.Mvc.Universe.Test/MyTested.AspNetCore.Mvc.Universe.Test.csproj" --configuration Release --no-build
- cmd: dotnet test "test/MyTested.AspNetCore.Mvc.ViewComponents.Attributes.Test/MyTested.AspNetCore.Mvc.ViewComponents.Attributes.Test.csproj" --configuration Release --no-build
- cmd: dotnet test "test/MyTested.AspNetCore.Mvc.ViewComponents.Results.Test/MyTested.AspNetCore.Mvc.ViewComponents.Results.Test.csproj" --configuration Release --no-build
- cmd: dotnet test "test/MyTested.AspNetCore.Mvc.ViewComponents.Test/MyTested.AspNetCore.Mvc.ViewComponents.Test.csproj" --configuration Release --no-build
- cmd: dotnet test "test/MyTested.AspNetCore.Mvc.ViewData.Test/MyTested.AspNetCore.Mvc.ViewData.Test.csproj" --configuration Release --no-build
- cmd: dotnet test "test/MyTested.AspNetCore.Mvc.ViewFeatures.Test/MyTested.AspNetCore.Mvc.ViewFeatures.Test.csproj" --configuration Release --no-build
